In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/stations.csv")

In [4]:
df.head()

         station_id           name sector       status
0  station-north-01    North Ridge  North       Active
1  station-north-02     North Gate  North       Active
2   station-west-01  West Junction   West       Active
3   station-west-02   West Outpost   West       Active
4   station-east-01    East Quarry   East  Maintenance

In [5]:
df.columns

Index(['station_id', 'name', 'sector', 'status'], dtype='str')

In [6]:
df.station_id.unique()

<StringArray>
['station-north-01', 'station-north-02',  'station-west-01',
  'station-west-02',  'station-east-01',  'station-east-02',
 'station-south-01', 'station-south-02']
Length: 8, dtype: str

In [7]:
df.status.unique()

<StringArray>
['Active', 'Maintenance', 'Offline']
Length: 3, dtype: str

In [10]:
df.shape

(8, 4)

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [14]:
df2 = pd.read_csv("../data/activity_readings.csv")

In [15]:
df2.shape

(2092, 4)

In [16]:
df2.columns

Index(['event_id', 'source_id', 'timestamp', 'value'], dtype='str')

In [18]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2092 entries, 0 to 2091
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   event_id   2090 non-null   str
 1   source_id  2090 non-null   str
 2   timestamp  2091 non-null   str
 3   value      2090 non-null   str
dtypes: str(4)
memory usage: 65.5 KB

In [27]:
df2.timestamp.sort_values().unique()

<StringArray>
['2026-09-09T08:00:00Z', '2026-09-09T08:01:00Z', '2026-09-09T08:02:00Z',
 '2026-09-09T08:03:00Z', '2026-09-09T08:04:00Z', '2026-09-09T08:05:00Z',
 '2026-09-09T08:06:00Z', '2026-09-09T08:07:00Z', '2026-09-09T08:08:00Z',
 '2026-09-09T08:09:00Z',
 ...
 '2026-09-09T12:13:00Z', '2026-09-09T12:14:00Z', '2026-09-09T12:15:00Z',
 '2026-09-09T12:16:00Z', '2026-09-09T12:17:00Z', '2026-09-09T12:18:00Z',
 '2026-09-09T12:19:00Z', '2026-13-45T99:00:00Z',           'not-a-date',
                    nan]
Length: 263, dtype: str

In [33]:
north_readings = df2[df2["source_id"] == "station-north-01"]

In [34]:
north_readings.head()

   event_id         source_id             timestamp value
2    e00003  station-north-01  2026-09-09T08:00:00Z  44.5
10   e00011  station-north-01  2026-09-09T08:01:00Z  41.1
18   e00019  station-north-01  2026-09-09T08:02:00Z  42.1
26   e00027  station-north-01  2026-09-09T08:03:00Z  42.6
34   e00035  station-north-01  2026-09-09T08:04:00Z  37.5

In [45]:
north_values = pd.to_numeric(north_readings["value"], errors="coerce")

In [50]:
print("north values count:", north_values.count())
print("north values min:", north_values.min())
print("north values max:", north_values.max())
print("north values mean:", north_values.mean())

north values count: 261
north values min: 22.0
north values max: 61.0
north values mean: 40.4551724137931

In [51]:
east_readings = df2[df2["source_id"] == "station-east-01"]

In [56]:
east_values = pd.to_numeric(east_readings["value"], errors="coerce")

In [57]:
print("east values count:", east_values.count())
print("east values min:", east_values.min())
print("east values max:", east_values.max())
print("east values mean:", east_values.mean())

east values count: 260
east values min: 19.4
east values max: 39.0
east values mean: 24.996153846153845

In [58]:
north_datetime = pd.to_datetime(north_readings["timestamp"], errors="coerce")

In [63]:
north_datetime.isna().sum()

np.int64(0)

In [64]:
north_readings[north_datetime.isna()]

Empty DataFrame
Columns: [event_id, source_id, timestamp, value]
Index: []

In [65]:
parsed_dates = pd.to_datetime(df2["timestamp"], errors="coerce")

parsed_values = pd.to_numeric(df2["value"], errors="coerce")

In [66]:
print("missing event_id:", df2["event_id"].isna().sum())
print("missing source_id:", df2["source_id"].isna().sum())
print("invalid timestamp:", parsed_dates.isna().sum())
print("invalid value:", parsed_values.isna().sum())

missing event_id: 2
missing source_id: 2
invalid timestamp: 3
invalid value: 5